In [63]:
import pandas as pd

print("Pandas working successfully")

Pandas working successfully

In [64]:
df = pd.read_csv(r"D:\Credit-card-analytics-pipeline\data\raw\credit_card_transactions-ibm_v2.csv")

In [65]:
df.head()

,User,Card,Year,Month,Day,Time,Amount,Use Chip,Merchant Name,Merchant City,Merchant State,Zip,MCC,Errors?,Is Fraud?
0,0,0,2002,9,1,06:21,$134.09,Swipe Transaction,3527213246127876953,La Verne,CA,91750.0,5300,NaN,No
1,0,0,2002,9,1,06:42,$38.48,Swipe Transaction,-727612092139916043,Monterey Park,CA,91754.0,5411,NaN,No
2,0,0,2002,9,2,06:22,$120.34,Swipe Transaction,-727612092139916043,Monterey Park,CA,91754.0,5411,NaN,No
3,0,0,2002,9,2,17:45,$128.95,Swipe Transaction,3414527459579106770,Monterey Park,CA,91754.0,5651,NaN,No
4,0,0,2002,9,3,06:23,$104.71,Swipe Transaction,5817218446178736267,La Verne,CA,91750.0,5912,NaN,No

In [66]:
# dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24386900 entries, 0 to 24386899
Data columns (total 15 columns):
 #   Column          Dtype
---  ------          -----
 0   User            int64
 1   Card            int64
 2   Year            int64
 3   Month           int64
 4   Day             int64
 5   Time            str
 6   Amount          str
 7   Use Chip        str
 8   Merchant Name   int64
 9   Merchant City   str
 10  Merchant State  str
 11  Zip             float64
 12  MCC             int64
 13  Errors?         str
 14  Is Fraud?       str
dtypes: float64(1), int64(7), str(7)
memory usage: 2.7 GB

In [67]:
df['Use Chip'].unique()
df['Use Chip'].value_counts()

Use Chip
Swipe Transaction     15386082
Chip Transaction       6287598
Online Transaction     2713220
Name: count, dtype: int64

In [68]:
df['Is Fraud?'].unique()
df['Is Fraud?'].value_counts()

Is Fraud?
No     24357143
Yes       29757
Name: count, dtype: int64

In [69]:
df['Errors?'].unique()
df['Errors?'].value_counts()

Errors?
Insufficient Balance                                   242783
Bad PIN                                                 58918
Technical Glitch                                        48157
Bad Card Number                                         13321
Bad CVV                                                 10740
Bad Expiration                                          10716
Bad Zipcode                                              2079
Bad PIN,Insufficient Balance                              581
Insufficient Balance,Technical Glitch                     457
Bad PIN,Technical Glitch                                  128
Bad Card Number,Insufficient Balance                      122
Bad CVV,Insufficient Balance                               89
Bad Expiration,Insufficient Balance                        78
Bad Card Number,Bad CVV                                    60
Bad Card Number,Bad Expiration                             54
Bad Expiration,Bad CVV                                     47
Bad Expiration,Technical Glitch                            32
Bad Card Number,Technical Glitch                           25
Bad CVV,Technical Glitch                                   21
Bad Zipcode,Insufficient Balance                           13
Bad Zipcode,Technical Glitch                                7
Bad Card Number,Bad Expiration,Insufficient Balance         2
Bad Card Number,Bad Expiration,Technical Glitch             1
Name: count, dtype: int64

In [70]:
#sample dataset

df_sample = df.sample(n = 100000, random_state = 42)

In [71]:
df_sample.to_csv(r"D:\Credit-card-analytics-pipeline\data\processed\transactions_sample.csv",
    index=False)

In [72]:
df = pd.read_csv(r"D:\Credit-card-analytics-pipeline\data\processed\transactions_sample.csv")

In [73]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   User            100000 non-null  int64
 1   Card            100000 non-null  int64
 2   Year            100000 non-null  int64
 3   Month           100000 non-null  int64
 4   Day             100000 non-null  int64
 5   Time            100000 non-null  str
 6   Amount          100000 non-null  str
 7   Use Chip        100000 non-null  str
 8   Merchant Name   100000 non-null  int64
 9   Merchant City   100000 non-null  str
 10  Merchant State  88782 non-null   str
 11  Zip             88134 non-null   float64
 12  MCC             100000 non-null  int64
 13  Errors?         1576 non-null    str
 14  Is Fraud?       100000 non-null  str
dtypes: float64(1), int64(7), str(7)
memory usage: 11.4 MB

In [74]:
df.columns = df.columns.str.lower()

In [75]:
df.columns = df.columns.str.replace(' ', '_')
df.columns = df.columns.str.replace('?', '', regex = False)

In [76]:
df.duplicated().sum()

np.int64(0)

In [77]:
df = df.drop_duplicates()

In [78]:
df.isnull().sum()

user                  0
card                  0
year                  0
month                 0
day                   0
time                  0
amount                0
use_chip              0
merchant_name         0
merchant_city         0
merchant_state    11218
zip               11866
mcc                   0
errors            98424
is_fraud              0
dtype: int64

In [79]:
df['merchant_state'] = df['merchant_state'].fillna('unknown')

In [80]:
df['zip'] = df['zip'].fillna(0)

In [81]:
df['errors'] = df['errors'].fillna('No error')

In [82]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   user            100000 non-null  int64
 1   card            100000 non-null  int64
 2   year            100000 non-null  int64
 3   month           100000 non-null  int64
 4   day             100000 non-null  int64
 5   time            100000 non-null  str
 6   amount          100000 non-null  str
 7   use_chip        100000 non-null  str
 8   merchant_name   100000 non-null  int64
 9   merchant_city   100000 non-null  str
 10  merchant_state  100000 non-null  str
 11  zip             100000 non-null  float64
 12  mcc             100000 non-null  int64
 13  errors          100000 non-null  str
 14  is_fraud        100000 non-null  str
dtypes: float64(1), int64(7), str(7)
memory usage: 11.4 MB

In [83]:
df['amount'] = df['amount'].str.replace('$', '', regex = False)

In [84]:
df['amount'] = df['amount'].astype(float)

In [85]:
df.head()

,user,card,year,month,day,time,amount,use_chip,merchant_name,merchant_city,merchant_state,zip,mcc,errors,is_fraud
0,1470,0,2019,7,10,00:11,59.18,Chip Transaction,-6853385250336487907,Harwood,MD,20776.0,5813,No error,No
1,822,1,2019,1,14,22:12,280.91,Online Transaction,4241336128694185533,ONLINE,unknown,0.0,4814,No error,No
2,41,3,2010,3,15,07:07,-144.00,Swipe Transaction,190253443608377572,Hemet,CA,92543.0,3359,No error,No
3,1084,0,2015,9,20,14:58,6.76,Chip Transaction,-7837310524365334241,Littleton,CO,80122.0,5300,No error,No
4,1384,0,2014,10,12,11:44,9.17,Swipe Transaction,-5023497618971072366,Gardner,KS,66030.0,5812,No error,No

In [86]:
df['transaction_date'] = pd.to_datetime(
    df[['year','month','day']])

In [87]:
df['transaction_datetime'] = pd.to_datetime(
    df['transaction_date'].astype(str) + ' ' + df['time'])

In [88]:
df[['transaction_date', 'transaction_datetime']].head()

  transaction_date transaction_datetime
0       2019-07-10  2019-07-10 00:11:00
1       2019-01-14  2019-01-14 22:12:00
2       2010-03-15  2010-03-15 07:07:00
3       2015-09-20  2015-09-20 14:58:00
4       2014-10-12  2014-10-12 11:44:00

In [89]:
df['transaction_datetime'].dtype

dtype('<M8[us]')

In [90]:
df['is_fraud'].value_counts()

is_fraud
No     99883
Yes      117
Name: count, dtype: int64

In [91]:
df['is_fraud_flag'] = df['is_fraud'].map({
    'Yes': 1,
    'No':0
})

In [92]:
df['errors'].value_counts()

errors
No error                                 98424
Insufficient Balance                      1003
Bad PIN                                    228
Technical Glitch                           195
Bad Card Number                             50
Bad Expiration                              44
Bad CVV                                     42
Bad Zipcode                                  7
Insufficient Balance,Technical Glitch        3
Bad Card Number,Insufficient Balance         2
Bad Card Number,Bad CVV                      1
Bad CVV,Insufficient Balance                 1
Name: count, dtype: int64

In [93]:
df['error_flag'] = df['errors'].apply(
    lambda x: 0 if x == 'No Error' else 1
)

In [94]:
df[['is_fraud', 'is_fraud_flag', 'errors', 'error_flag']].head()

  is_fraud  is_fraud_flag    errors  error_flag
0       No              0  No error           1
1       No              0  No error           1
2       No              0  No error           1
3       No              0  No error           1
4       No              0  No error           1

In [95]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   user                  100000 non-null  int64
 1   card                  100000 non-null  int64
 2   year                  100000 non-null  int64
 3   month                 100000 non-null  int64
 4   day                   100000 non-null  int64
 5   time                  100000 non-null  str
 6   amount                100000 non-null  float64
 7   use_chip              100000 non-null  str
 8   merchant_name         100000 non-null  int64
 9   merchant_city         100000 non-null  str
 10  merchant_state        100000 non-null  str
 11  zip                   100000 non-null  float64
 12  mcc                   100000 non-null  int64
 13  errors                100000 non-null  str
 14  is_fraud              100000 non-null  str
 15  transaction_date      100000 non-null  datetime64[us]
 16  transaction_datetime  100000 non-null  datetime64[us]
 17  is_fraud_flag         100000 non-null  int64
 18  error_flag            100000 non-null  int64
dtypes: datetime64[us](2), float64(2), int64(9), str(6)
memory usage: 14.5 MB

In [96]:
df = df.drop(
    columns=['year', 'month', 'day', 'time', 'is_fraud']
)

In [97]:
df.columns

Index(['user', 'card', 'amount', 'use_chip', 'merchant_name', 'merchant_city',
       'merchant_state', 'zip', 'mcc', 'errors', 'transaction_date',
       'transaction_datetime', 'is_fraud_flag', 'error_flag'],
      dtype='str')

In [98]:
#Total Transaction Amount
df['amount'].sum()

np.float64(4335427.52)

In [99]:
#Average Transaction Amount
df['amount'].mean()

np.float64(43.3542752)

In [100]:
#Fraud Rate
df['is_fraud_flag'].mean()*100

np.float64(0.117)

In [101]:
df['use_chip'].value_counts()

use_chip
Swipe Transaction     63128
Chip Transaction      25685
Online Transaction    11187
Name: count, dtype: int64

In [102]:
df.groupby('use_chip')['is_fraud_flag'].mean() * 100

use_chip
Chip Transaction      0.050613
Online Transaction    0.706177
Swipe Transaction     0.039602
Name: is_fraud_flag, dtype: float64

In [103]:
df.groupby('merchant_city')['is_fraud_flag'].mean().sort_values(ascending=False).head(10)*100

merchant_city
Istanbul          100.00
Algiers           100.00
Green Springs     100.00
Port au Prince    100.00
Abuja              50.00
Attica             50.00
New Cumberland     50.00
Park City          50.00
Rome               31.25
Strasburg          20.00
Name: is_fraud_flag, dtype: float64

In [104]:
city_stats = df.groupby('merchant_city').agg(
    total_transactions = ('is_fraud_flag', 'count'),
    fraud_rate=('is_fraud_flag', 'mean')
)

In [105]:
city_stats.head()

               total_transactions  fraud_rate
merchant_city
Abbeville                      86         0.0
Abbotsford                      1         0.0
Aberdeen                       18         0.0
Abilene                        60         0.0
Abingdon                       13         0.0

In [106]:
filtered_cities = city_stats[
    city_stats['total_transactions'] >= 100
]

In [107]:
filtered_cities.sort_values(
    by = 'fraud_rate',
    ascending = False
).head(10)

               total_transactions  fraud_rate
merchant_city
ONLINE                      11218    0.007042
San Jose                      303    0.003300
Alpharetta                    198    0.000000
Albuquerque                   302    0.000000
Acworth                       134    0.000000
Annandale                     103    0.000000
Arlington                     134    0.000000
Arnold                        121    0.000000
Atlanta                       469    0.000000
Auburn                        139    0.000000

In [108]:
mcc_stats = df.groupby('mcc').agg(
    total_transactions = ('is_fraud_flag', 'count'),
    fraud_rate = ('is_fraud_flag', 'mean')
)

In [109]:
mcc_stats.sort_values(
    by = 'fraud_rate',
    ascending = False
).head(10)

      total_transactions  fraud_rate
mcc
4411                   1    1.000000
5733                   5    0.400000
3075                   5    0.200000
5816                  20    0.200000
5045                  19    0.105263
5094                  46    0.086957
5712                  28    0.071429
5732                  68    0.044118
3389                  75    0.026667
5977                  43    0.023256

In [110]:
filtered_mcc = mcc_stats[
    mcc_stats['total_transactions'] >= 100
]

In [111]:
filtered_mcc.sort_values(
    by = 'fraud_rate',
    ascending = False
).head(10)

      total_transactions  fraud_rate
mcc
3775                 111    0.018018
3596                 127    0.015748
3509                 140    0.014286
7011                 140    0.014286
5251                 260    0.011538
3771                 108    0.009259
3640                 111    0.009009
3684                 120    0.008333
4722                 261    0.007663
5310                1867    0.005356

In [112]:
df['transaction_hour'] = df['transaction_datetime'].dt.hour

In [113]:
hourly_stats = df.groupby('transaction_hour').agg(
    total_transactions = ('amount', 'count'),
    fraud_rate = ('is_fraud_flag', 'mean')
)

In [114]:
hourly_stats

                  total_transactions  fraud_rate
transaction_hour
0                               1016    0.001969
1                                802    0.000000
2                                852    0.000000
3                                757    0.003963
4                                803    0.003736
5                               1275    0.002353
6                               5437    0.000368
7                               6826    0.001025
8                               6658    0.001051
9                               6619    0.001058
10                              6833    0.002342
11                              7154    0.001817
12                              7156    0.001397
13                              6824    0.001172
14                              6615    0.001663
15                              6489    0.001387
16                              6456    0.000620
17                              3709    0.000809
18                              3427    0.000584
19                              3593    0.001670
20                              3299    0.000000
21                              3149    0.000000
22                              3037    0.000329
23                              1214    0.000000

In [115]:
daily_stats = df.groupby('transaction_date').agg(
    total_transactions= ('amount', 'count'),
    total_amount = ('amount', 'sum'),
    fraud_rate = ('is_fraud_flag', 'mean')

)

In [116]:
daily_stats.head()

                  total_transactions  total_amount  fraud_rate
transaction_date
1991-01-17                         1        -99.00         0.0
1991-05-27                         1         68.04         0.0
1991-05-29                         1       1122.29         0.0
1991-07-17                         1         74.21         0.0
1991-09-19                         1         57.00         0.0

In [117]:
negative_transactions = df[
    df['amount'] < 0
]

In [118]:
negative_transactions.shape

(5078, 15)

In [119]:
negative_transactions.head()

,user,card,amount,use_chip,merchant_name,merchant_city,merchant_state,zip,mcc,errors,transaction_date,transaction_datetime,is_fraud_flag,error_flag,transaction_hour
2,41,3,-144.0,Swipe Transaction,190253443608377572,Hemet,CA,92543.0,3359,No error,2010-03-15,2010-03-15 07:07:00,0,1,7
35,972,0,-63.0,Swipe Transaction,1799189980464955940,Plano,TX,75023.0,5499,No error,2011-09-13,2011-09-13 13:02:00,0,1,13
61,1148,0,-85.0,Swipe Transaction,1799189980464955940,Van Wert,OH,45891.0,5499,No error,2014-10-23,2014-10-23 06:59:00,0,1,6
70,206,1,-81.0,Chip Transaction,-1288082279022882052,Muse,PA,15350.0,5499,No error,2017-09-30,2017-09-30 14:25:00,0,1,14
118,1274,0,-59.0,Chip Transaction,-1288082279022882052,Gainesville,FL,32608.0,5499,No error,2017-06-07,2017-06-07 07:27:00,0,1,7

In [120]:
df['errors'] = df['errors'].str.lower()

In [121]:
df['error_flag'] = df['errors'].apply(
    lambda x: 0 if x == 'no error' else 1
)

In [122]:
df[['errors', 'error_flag']].head()

     errors  error_flag
0  no error           0
1  no error           0
2  no error           0
3  no error           0
4  no error           0

In [123]:
df.to_csv(
    r"D:\Credit-card-analytics-pipeline\data\processed\clean_transactions.csv",
    index=False
)