In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
engine = create_engine(
    'postgresql://postgres:123456789@localhost:5432/credit_card_pipeline'
    )

In [3]:
query = "SELECT COUNT(*) FROM transactions LIMIT 5"

In [4]:
pd.read_sql(query, engine)

    count
0  100000

In [5]:
query = "SELECT * FROM transactions LIMIT 5"

In [6]:
query = """
SELECT
    SUM(amount) AS total_transaction_amount
FROM transactions
"""

In [7]:
pd.read_sql(query, engine)

   total_transaction_amount
0                4335427.52

In [8]:
query = """
SELECT
    AVG(is_fraud_flag) * 100 AS fraud_rate
FROM transactions
"""

In [9]:
pd.read_sql(query,engine)

   fraud_rate
0       0.117

In [10]:
query = """
SELECT
    use_chip,
    COUNT(*) AS total_transactions,
    AVG(is_fraud_flag) * 100 AS fraud_rate
FROM transactions
GROUP BY use_chip
ORDER BY fraud_rate DESC
"""

In [11]:
pd.read_sql(query, engine)

             use_chip  total_transactions  fraud_rate
0  Online Transaction               11187    0.706177
1    Chip Transaction               25685    0.050613
2   Swipe Transaction               63128    0.039602

In [12]:
query = """
SELECT
    transaction_hour,
    COUNT(*) AS total_transactions,
    AVG(is_fraud_flag) * 100 AS fraud_rate
FROM transactions
GROUP BY transaction_hour
ORDER BY transaction_hour
"""

In [13]:
pd.read_sql(query, engine)

    transaction_hour  total_transactions  fraud_rate
0                  0                1016    0.196850
1                  1                 802    0.000000
2                  2                 852    0.000000
3                  3                 757    0.396301
4                  4                 803    0.373599
5                  5                1275    0.235294
6                  6                5437    0.036785
7                  7                6826    0.102549
8                  8                6658    0.105137
9                  9                6619    0.105756
10                10                6833    0.234158
11                11                7154    0.181717
12                12                7156    0.139743
13                13                6824    0.117233
14                14                6615    0.166289
15                15                6489    0.138696
16                16                6456    0.061958
17                17                3709    0.080884
18                18                3427    0.058360
19                19                3593    0.166991
20                20                3299    0.000000
21                21                3149    0.000000
22                22                3037    0.032927
23                23                1214    0.000000

In [14]:
query = """
SELECT
    DATE_TRUNC('month', transaction_datetime) AS transaction_month,
    COUNT(*) AS total_transactions,
    SUM(amount) AS total_amount,
    AVG(is_fraud_flag) * 100 AS fraud_rate
FROM transactions
GROUP BY transaction_month
ORDER BY transaction_month;
"""

In [15]:
pd.read_sql(query, engine)

    transaction_month  total_transactions  total_amount  fraud_rate
0          1991-01-01                   1        -99.00         0.0
1          1991-05-01                   2       1190.33         0.0
2          1991-07-01                   1         74.21         0.0
3          1991-09-01                   1         57.00         0.0
4          1991-10-01                   1         79.38         0.0
..                ...                 ...           ...         ...
336        2019-10-01                 609      27104.51         0.0
337        2019-11-01                 564      23633.43         0.0
338        2019-12-01                 598      22367.83         0.0
339        2020-01-01                 697      30507.16         0.0
340        2020-02-01                 712      29161.68         0.0

[341 rows x 4 columns]